
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MarketplaceC2DContractArtifactJson from '../../contracts/marketplace_c2d/target/marketplace_c2d_contract-MarketplaceC2D.json' with { type: 'json' };
export const MarketplaceC2DContractArtifact = loadContractArtifact(MarketplaceC2DContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MarketplaceC2D;
 */
export class MarketplaceC2DContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MarketplaceC2DContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MarketplaceC2DContract {
    return Contract.at(address, MarketplaceC2DContract.artifact, wallet) as MarketplaceC2DContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, vk_hash: FieldLike) {
    return new DeployMethod<MarketplaceC2DContract>(PublicKeys.default(), wallet, MarketplaceC2DContractArtifact, (instance, wallet) => MarketplaceC2DContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, vk_hash: FieldLike) {
    return new DeployMethod<MarketplaceC2DContract>(publicKeys, wallet, MarketplaceC2DContractArtifact, (instance, wallet) => MarketplaceC2DContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MarketplaceC2DContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MarketplaceC2DContract['methods'][M]>
  ) {
    return new DeployMethod<MarketplaceC2DContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MarketplaceC2DContractArtifact,
      (instance, wallet) => MarketplaceC2DContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MarketplaceC2DContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MarketplaceC2DContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'vk_hash' | 'next_listing_id' | 'listings' | 'listing_notes' | 'escrows' | 'results'> {
      return {
        vk_hash: {
      slot: new Fr(1n),
    },
next_listing_id: {
      slot: new Fr(3n),
    },
listings: {
      slot: new Fr(4n),
    },
listing_notes: {
      slot: new Fr(5n),
    },
escrows: {
      slot: new Fr(6n),
    },
results: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'vk_hash' | 'next_listing_id' | 'listings' | 'listing_notes' | 'escrows' | 'results'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(vk_hash: field) */
    constructor: ((vk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_listing(h_d: field, price: field, token: struct) */
    create_listing: ((h_d: FieldLike, price: FieldLike, token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deliver_query_result(listing_id: field, buyer: struct, h_d: field, result_value: field, verification_key: array, proof: array, public_inputs: array) */
    deliver_query_result: ((listing_id: FieldLike, buyer: AztecAddressLike, h_d: FieldLike, result_value: FieldLike, verification_key: FieldLike[], proof: FieldLike[], public_inputs: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_listing(listing_id: field) */
    get_listing: ((listing_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_listing_id() */
    get_next_listing_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_vk_hash() */
    get_vk_hash: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** lock_payment(listing_id: field, seller: struct, amount: field, token: struct, deadline: field) */
    lock_payment: ((listing_id: FieldLike, seller: AztecAddressLike, amount: FieldLike, token: AztecAddressLike, deadline: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refund(listing_id: field, seller: struct) */
    refund: ((listing_id: FieldLike, seller: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
