// MarketplaceC2D E2E test.
//
// Mirrors the structure of test/e2e/marketplace.test.ts (Tier 1) but
// exercises the C2D flow:
//
//   1. Deploy Token, MarketplaceC2D (with the offchain circuit's VK hash).
//   2. Mint test tokens to the buyer.
//   3. Seller creates a listing committing to H(D).
//   4. Buyer locks payment against the listing.
//   5. Seller calls deliver_query_result with the real proof from the
//      offchain circuit. The contract verifies via verify_honk_proof,
//      releases the escrow, and delivers a result note to the buyer.
//
// The proof, VK, and public_inputs are read from c2d/test/fixtures/, which
// is populated by scripts/refresh_fixtures.sh from the offchain circuit's
// target/proof/ directory.

import { describe, it, expect, beforeAll, afterAll } from "@jest/globals";
import { createAztecNodeClient } from "@aztec/aztec.js/node";
import { Fr } from "@aztec/aztec.js/fields";
import { AztecAddress } from "@aztec/aztec.js/addresses";
import { SponsoredFeePaymentMethod } from "@aztec/aztec.js/fee";
import { getContractInstanceFromInstantiationParams } from "@aztec/aztec.js/contracts";
import { AccountManager } from "@aztec/aztec.js/wallet";
import { GrumpkinScalar } from "@aztec/foundation/curves/grumpkin";
import { createLogger } from "@aztec/foundation/log";
import { SPONSORED_FPC_SALT } from "@aztec/constants";
import { SponsoredFPCContractArtifact } from "@aztec/noir-contracts.js/SponsoredFPC";
import { TokenContract } from "@aztec/noir-contracts.js/Token";
import { EmbeddedWallet } from "@aztec/wallets/embedded";
import { MarketplaceC2DContract } from "../artifacts/MarketplaceC2D.js";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const NODE_URL = process.env.AZTEC_NODE_URL || "http://localhost:8080";
const DEPLOY_TIMEOUT = 120_000;
const TX_TIMEOUT = 60_000;

const logger = createLogger("e2e:marketplace_c2d");

// Listing parameters.
const PRICE = new Fr(100n);

// ---------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------
//
// The proof, VK, and public_inputs are generated by the offchain circuit
// (c2d/offchain-circuit) using `bb prove`. They are copied into the
// fixtures/ directory by scripts/refresh_fixtures.sh.

interface ProofFile {
  proof: string[];
  vk_hash: string;
  bb_version: string;
  scheme: string;
}

interface VkFile {
  vk: string[];
  hash: string;
  bb_version: string;
  scheme: string;
}

interface PublicInputsFile {
  public_inputs: string[];
  bb_version: string;
  scheme: string;
}

function loadFixtures() {
  const fixturesDir = join(__dirname, "..", "fixtures");
  const proof = JSON.parse(
    readFileSync(join(fixturesDir, "proof.json"), "utf8"),
  ) as ProofFile;
  const vk = JSON.parse(
    readFileSync(join(fixturesDir, "vk.json"), "utf8"),
  ) as VkFile;
  const publicInputs = JSON.parse(
    readFileSync(join(fixturesDir, "public_inputs.json"), "utf8"),
  ) as PublicInputsFile;

  return {
    proofFields: proof.proof.map((hex) => Fr.fromString(hex)),
    vkFields: vk.vk.map((hex) => Fr.fromString(hex)),
    vkHash: Fr.fromString(vk.hash),
    publicInputsFields: publicInputs.public_inputs.map((hex) =>
      Fr.fromString(hex),
    ),
    // Convenience: pull the named public inputs out by position.
    // Order is fixed by the offchain circuit:
    //   [0] h_d, [1] params_hash, [2] result_value, [3] window_days
    h_d: Fr.fromString(publicInputs.public_inputs[0]),
    params_hash: Fr.fromString(publicInputs.public_inputs[1]),
    result_value: Fr.fromString(publicInputs.public_inputs[2]),
    window_days: Fr.fromString(publicInputs.public_inputs[3]),
  };
}

// ---------------------------------------------------------------
// Sponsored FPC
// ---------------------------------------------------------------

async function getSponsoredFPCInstance() {
  return await getContractInstanceFromInstantiationParams(
    SponsoredFPCContractArtifact,
    { salt: new Fr(SPONSORED_FPC_SALT) },
  );
}

// ---------------------------------------------------------------
// Test Suite
// ---------------------------------------------------------------

describe("MarketplaceC2D E2E", () => {
  let wallet: EmbeddedWallet;
  let sponsoredPaymentMethod: SponsoredFeePaymentMethod;
  let sellerAccount: AccountManager;
  let buyerAccount: AccountManager;
  let token: TokenContract;
  let marketplace: MarketplaceC2DContract;
  let fixtures: ReturnType<typeof loadFixtures>;

  beforeAll(async () => {
    fixtures = loadFixtures();
    logger.info(`Loaded fixtures: H(D) = ${fixtures.h_d.toString()}`);
    logger.info(`Result value = ${fixtures.result_value.toString()}`);
    logger.info(`VK hash = ${fixtures.vkHash.toString()}`);

    const node = createAztecNodeClient(NODE_URL);
    wallet = await EmbeddedWallet.create(node, { ephemeral: true });

    const sponsoredFPC = await getSponsoredFPCInstance();
    await wallet.registerContract(sponsoredFPC, SponsoredFPCContractArtifact);
    sponsoredPaymentMethod = new SponsoredFeePaymentMethod(sponsoredFPC.address);

    // Create seller and buyer accounts.
    sellerAccount = await wallet.createSchnorrAccount(
      Fr.random(),
      Fr.random(),
      GrumpkinScalar.random(),
    );
    buyerAccount = await wallet.createSchnorrAccount(
      Fr.random(),
      Fr.random(),
      GrumpkinScalar.random(),
    );

    // Deploy both accounts. `from: AztecAddress.ZERO` because the account
    // doesn't exist on chain yet and so can't authenticate its own deployment;
    // this is the same pattern Tier 1's marketplace test uses.
    await (await sellerAccount.getDeployMethod()).send({
      from: AztecAddress.ZERO,
      fee: { paymentMethod: sponsoredPaymentMethod },
      wait: { timeout: DEPLOY_TIMEOUT },
    });
    logger.info(`Seller account: ${sellerAccount.address}`);

    await (await buyerAccount.getDeployMethod()).send({
      from: AztecAddress.ZERO,
      fee: { paymentMethod: sponsoredPaymentMethod },
      wait: { timeout: DEPLOY_TIMEOUT },
    });
    logger.info(`Buyer account: ${buyerAccount.address}`);

    // Cross-register so each side's PXE discovers notes from the other.
    await wallet.registerSender(sellerAccount.address, "seller");
    await wallet.registerSender(buyerAccount.address, "buyer");

    // Deploy a test token. Mint to the buyer in the same transaction by
    // using the seller as admin (any account works; this is test setup).
    const tokenDeploy = TokenContract.deploy(
      wallet,
      sellerAccount.address,
      "Test USDC",
      "USDC",
      6,
    );
    await tokenDeploy.simulate({ from: sellerAccount.address });
    const { contract: token_ } = await tokenDeploy.send({
      from: sellerAccount.address,
      fee: { paymentMethod: sponsoredPaymentMethod },
      wait: { timeout: DEPLOY_TIMEOUT },
    });
    token = token_;
    logger.info(`Token: ${token.address}`);

    // Mint tokens to the buyer's public balance, then move to private so the
    // marketplace can transfer them from the buyer's private balance to its
    // own public balance via transfer_to_public on lock.
    await token.methods
      .mint_to_public(buyerAccount.address, 1000n)
      .simulate({ from: sellerAccount.address });
    await token.methods
      .mint_to_public(buyerAccount.address, 1000n)
      .send({
        from: sellerAccount.address,
        fee: { paymentMethod: sponsoredPaymentMethod },
        wait: { timeout: TX_TIMEOUT },
      });
    logger.info("Minted 1000 tokens to buyer (public)");

    await token.methods
      .transfer_to_private(buyerAccount.address, 1000n)
      .simulate({ from: buyerAccount.address });
    await token.methods
      .transfer_to_private(buyerAccount.address, 1000n)
      .send({
        from: buyerAccount.address,
        fee: { paymentMethod: sponsoredPaymentMethod },
        wait: { timeout: TX_TIMEOUT },
      });
    logger.info("Moved 1000 tokens to buyer's private balance");

    // Deploy MarketplaceC2D with the VK hash from the proof artefacts.
    const marketplaceDeploy = MarketplaceC2DContract.deploy(
      wallet,
      fixtures.vkHash,
    );
    await marketplaceDeploy.simulate({ from: sellerAccount.address });
    const { contract: marketplace_ } = await marketplaceDeploy.send({
      from: sellerAccount.address,
      fee: { paymentMethod: sponsoredPaymentMethod },
      wait: { timeout: DEPLOY_TIMEOUT },
    });
    marketplace = marketplace_;
    logger.info(`MarketplaceC2D: ${marketplace.address}`);
  }, 600_000);

  afterAll(async () => {
    await wallet?.stop();
  });

  it("end-to-end: list, lock, deliver-with-proof, payment releases", async () => {
    // ---- Seller creates the listing ----
    await marketplace.methods
      .create_listing(fixtures.h_d, PRICE, token.address)
      .simulate({ from: sellerAccount.address });
    await marketplace.methods
      .create_listing(fixtures.h_d, PRICE, token.address)
      .send({
        from: sellerAccount.address,
        fee: { paymentMethod: sponsoredPaymentMethod },
        wait: { timeout: TX_TIMEOUT },
      });

    const listingId = new Fr(1n);
    const listing = await marketplace.methods
      .get_listing(listingId)
      .simulate({ from: sellerAccount.address });
    expect(listing.result.active).toBe(true);
    expect(BigInt(listing.result.price)).toBe(PRICE.toBigInt());
    logger.info("Listing created");

    // ---- Buyer locks payment ----
    const lockAction = token.methods.transfer_to_public(
      buyerAccount.address,
      marketplace.address,
      100n,
      0,
    );
    const authWit = await wallet.createAuthWit(buyerAccount.address, {
      caller: marketplace.address,
      action: lockAction,
    });
    const deadline = new Fr(1200n);

    await marketplace.methods
      .lock_payment(
        listingId,
        sellerAccount.address,
        PRICE,
        token.address,
        deadline,
      )
      .with({ authWitnesses: [authWit] })
      .simulate({ from: buyerAccount.address });
    await marketplace.methods
      .lock_payment(
        listingId,
        sellerAccount.address,
        PRICE,
        token.address,
        deadline,
      )
      .with({ authWitnesses: [authWit] })
      .send({
        from: buyerAccount.address,
        fee: { paymentMethod: sponsoredPaymentMethod },
        wait: { timeout: TX_TIMEOUT },
      });
    logger.info("Buyer locked 100 tokens against listing");

    // ---- Seller delivers the result with the proof ----
    // This is the load-bearing step: verify_honk_proof inside the private
    // function consumes the proof generated offchain.
    await marketplace.methods
      .deliver_query_result(
        listingId,
        buyerAccount.address,
        fixtures.h_d,
        fixtures.result_value,
        fixtures.vkFields,
        fixtures.proofFields,
        fixtures.publicInputsFields,
      )
      .simulate({ from: sellerAccount.address });
    await marketplace.methods
      .deliver_query_result(
        listingId,
        buyerAccount.address,
        fixtures.h_d,
        fixtures.result_value,
        fixtures.vkFields,
        fixtures.proofFields,
        fixtures.publicInputsFields,
      )
      .send({
        from: sellerAccount.address,
        fee: { paymentMethod: sponsoredPaymentMethod },
        // Delivery includes verify_honk_proof, so allow extra time for
        // the private-side proof of the contract call.
        wait: { timeout: 180_000 },
      });
    logger.info("Seller delivered result with verified proof");

    // ---- Assert payment moved ----
    const sellerBalance = await token.methods
      .balance_of_public(sellerAccount.address)
      .simulate({ from: sellerAccount.address });
    expect(BigInt(sellerBalance.result)).toBe(PRICE.toBigInt());
    logger.info(`Seller received ${sellerBalance.result} tokens`);
  }, 900_000);
});