
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MarketplaceContractArtifactJson from '../../contracts/marketplace/target/marketplace_contract-Marketplace.json' with { type: 'json' };
export const MarketplaceContractArtifact = loadContractArtifact(MarketplaceContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract Marketplace;
 */
export class MarketplaceContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, MarketplaceContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MarketplaceContract {
    return Contract.at(address, MarketplaceContract.artifact, wallet) as MarketplaceContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, registry: AztecAddressLike) {
    return new DeployMethod<MarketplaceContract>(PublicKeys.default(), wallet, MarketplaceContractArtifact, (instance, wallet) => MarketplaceContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, registry: AztecAddressLike) {
    return new DeployMethod<MarketplaceContract>(publicKeys, wallet, MarketplaceContractArtifact, (instance, wallet) => MarketplaceContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MarketplaceContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MarketplaceContract['methods'][M]>
  ) {
    return new DeployMethod<MarketplaceContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MarketplaceContractArtifact,
      (instance, wallet) => MarketplaceContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MarketplaceContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MarketplaceContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'registry' | 'listings' | 'next_listing_id' | 'listing_notes' | 'escrows' | 'data_notes'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
registry: {
      slot: new Fr(2n),
    },
listings: {
      slot: new Fr(3n),
    },
next_listing_id: {
      slot: new Fr(4n),
    },
listing_notes: {
      slot: new Fr(5n),
    },
escrows: {
      slot: new Fr(6n),
    },
data_notes: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'admin' | 'registry' | 'listings' | 'next_listing_id' | 'listing_notes' | 'escrows' | 'data_notes'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(admin: struct, registry: struct) */
    constructor: ((admin: AztecAddressLike, registry: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_listing(data_0: field, data_1: field, data_2: field, data_3: field, price: field, token: struct, category: field, value_min: field, value_max: field, device_id: field, attestor_id: field, registry_address: struct, signature: array, pub_key_x: array, pub_key_y: array) */
    create_listing: ((data_0: FieldLike, data_1: FieldLike, data_2: FieldLike, data_3: FieldLike, price: FieldLike, token: AztecAddressLike, category: FieldLike, value_min: FieldLike, value_max: FieldLike, device_id: FieldLike, attestor_id: FieldLike, registry_address: AztecAddressLike, signature: FieldLike[], pub_key_x: FieldLike[], pub_key_y: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** deliver_and_claim(listing_id: field, buyer: struct, data_0: field, data_1: field, data_2: field, data_3: field) */
    deliver_and_claim: ((listing_id: FieldLike, buyer: AztecAddressLike, data_0: FieldLike, data_1: FieldLike, data_2: FieldLike, data_3: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_listing(listing_id: field) */
    get_listing: ((listing_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_listing_id() */
    get_next_listing_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** lock_payment(listing_id: field, seller: struct, amount: field, token: struct, deadline: field) */
    lock_payment: ((listing_id: FieldLike, seller: AztecAddressLike, amount: FieldLike, token: AztecAddressLike, deadline: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refund(listing_id: field, seller: struct) */
    refund: ((listing_id: FieldLike, seller: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_registry(registry: struct) */
    set_registry: ((registry: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
